### ISSUE TITLE
Nakładanie się napisów na siebie

### ISSUE THREAD

**Issue by morfikov** [dagon666/napi#17]
Tak sobie analizuję konwertowanie tych napisów i coś mi się czasy rozjeżdżają, poniżej przykład.

Przed konwersją:

    00:05:56:Zmierzasz na pó³noc, czy po³udnie.
    00:05:58:Pó³noc.
    00:06:00:Wskakuj.
    00:06:02:Upewniê siê, | ¿e znajdziesz drogê.
    00:06:17:/- Dok¹d zmierzasz? | /- Portland.
    00:06:20:Portland jest na po³udniu mówi³e, | ¿e zmierzasz na pó³noc.

Po konwersji:

    38
    00:05:56,000 --> 00:05:59,000
    Zmierzasz na północ, czy południe.
    
    39
    00:05:58,000 --> 00:06:01,000
    Północ.
    
    40
    00:06:00,000 --> 00:06:03,000
    Wskakuj.
    
    41
    00:06:02,000 --> 00:06:05,000
    Upewnię się,
    że znajdziesz drogę.
    
    42
    00:06:17,000 --> 00:06:20,000
    /- Dokąd zmierzasz?
    /- Portland.
    
    43
    00:06:20,000 --> 00:06:23,000
    Portland jest na południu mówiłeś,
    że zmierzasz na północ.

Jak widać `38` się kończy później niż `39` się zaczyna, podobnie z `40` i  `41` ale już `42` i `43` są w porządku. W całym filmie jest szereg tego typu nałożonych napisów. Da radę jakoś te czasy zrównać, tak by się nie nakładały?

**Comment by dagon666** [comment]
@morfikov w koncu znalazlem chwile zeby sie tym zajac. Bylbym wdzieczny gdybys mogl sprawdzic z najnowsza wersja z galezi dev (a8a1949). subotage.sh powinien poprawiac "zazebiajace" sie napisy dla wszystkich formatow.

**Comment by morfikov** [comment]
Raczej już nie znajdę tamtych napisów, a od roku praktycznie nie korzystam z napisów w filmach. :)

**Comment by dagon666** [comment]
ok. mimo wszystko dzieki za pomoc. zamykam.
