### ISSUE TITLE
download unmatched subs

### ISSUE THREAD

**Issue by r8b7xy** [dagon666/napi#32]
Is there any way to download subs that aren't matched? e.g. Subs are UNAV but on napiprojekt there are other subs and I'd like to download them with napi.sh. yanked sub url: napiprojekt:dcb651f793c2f56a90b20180e1d1a6ef

**Comment by dagon666** [comment]
At the moment it's not possible, but I guess it would be very good to have this feature. It will be implemented in the next version

**Comment by dagon666** [comment]
napi.sh in version 2.0.0 implements this feature. Having a subtitles hash it's possible to obtain them with command:

`napi.sh download napiprojekt:dcb651f793c2f56a90b20180e1d1a6ef`
