### ISSUE TITLE
Brak subotage w AUR

### ISSUE THREAD

**Issue by Cysioland** [dagon666/napi#38]
W AUR brak wspomnianej w README paczki `bashnapi`, zamiast tego jest `napi-bash`, które "sugeruje" `subotage`, ale nie dostarcza go, ani `subotage` nie ma w AUR.

**Comment by JuniorJPDJ** [comment]
Potwierdzam.
Sam chciałem pisać

**Comment by dagon666** [comment]
The package has been restored in AUR as `bashnapi`.
